load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")

scala_library(
    name = "main",
    srcs = glob(["**/*.scala"]),
    resources = glob(["resources/**"]),
    visibility = ["//visibility:public"],
)
